spring:
  application:
    name: springboot
  main:
    allow-bean-definition-overriding: true

grpc:
  server:
    port: 9090
    inProcessName: test
  client:
    hello:
      address: localhost:9090
      negotiation-type: plaintext


